---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  namespace: landing
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: registry.cloud.cbh.kth.se/system/landing-api
          envFrom:
            - configMapRef:
                name: landing-api-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: system-ci-secret
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: landing
  labels:
    app.kubernetes.io/name: api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: api