---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  namespace: landing
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: registry.cloud.cbh.kth.se/system/landing-api
          envFrom:
            - configMapRef:
                name: landing-api-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: kthcloud-system-secret
      restartPolicy: Always