---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: landing-api-v2
  namespace: landing
  labels:
    app.kubernetes.io/name: landing-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: landing-api-v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: landing-api-v2
    spec:
      volumes:
        - name: vol-landing-config
          persistentVolumeClaim:
            claimName: pvc-landing-config
      containers:
        - name: landing-api-v2

          image: registry.cloud.cbh.kth.se/system/landing-api-v2
          envFrom:
            - configMapRef:
                name: landing-api-v2-config
          volumeMounts:
            - name: vol-landing-config
              mountPath: /etc/landing/config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: kthcloud-system-secret
      restartPolicy: Always