definitions:
  app.ErrorResponse:
    properties:
      errors:
        items:
          $ref: '#/definitions/app.errorPiece'
        type: array
    type: object
  app.errorPiece:
    properties:
      code:
        type: string
      msg:
        type: string
    type: object
  body.BindingError:
    properties:
      validationErrors:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
    type: object
  body.Capacities:
    properties:
      cpuCore:
        $ref: '#/definitions/body.CpuCoreCapacities'
      gpu:
        $ref: '#/definitions/body.GpuCapacities'
      hosts:
        items:
          $ref: '#/definitions/body.HostCapacities'
        type: array
      ram:
        $ref: '#/definitions/body.RamCapacities'
    type: object
  body.ClusterStats:
    properties:
      cluster:
        type: string
      podCount:
        type: integer
    type: object
  body.CpuCoreCapacities:
    properties:
      total:
        type: integer
    type: object
  body.GpuCapacities:
    properties:
      total:
        type: integer
    type: object
  body.GpuInfo:
    properties:
      hosts:
        items:
          $ref: '#/definitions/body.HostGpuInfo'
        type: array
    type: object
  body.HostCapacities:
    properties:
      displayName:
        type: string
      gpu:
        properties:
          count:
            type: integer
        type: object
      name:
        type: string
      ram:
        properties:
          total:
            type: integer
        type: object
      zone:
        description: |-
          Zone is the name of the zone where the host is located.
          This field might not yet be present in all responses, in which case ZoneID should be used.
        type: string
    type: object
  body.HostGpuInfo:
    properties:
      displayName:
        type: string
      gpus:
        items:
          $ref: '#/definitions/host_api.GpuInfo'
        type: array
      name:
        type: string
      zone:
        description: |-
          Zone is the name of the zone where the host is located.
          This field might not yet be present in all responses, in which case ZoneID should be used.
        type: string
    type: object
  body.HostInfo:
    properties:
      displayName:
        type: string
      name:
        type: string
      zone:
        description: |-
          Zone is the name of the zone where the host is located.
          This field might not yet be present in all responses, in which case ZoneID should be used.
        type: string
    type: object
  body.HostStatus:
    properties:
      cpu:
        properties:
          load:
            properties:
              cores:
                items:
                  type: integer
                type: array
              main:
                type: number
              max:
                type: number
            type: object
          temp:
            properties:
              cores:
                items:
                  type: integer
                type: array
              main:
                type: number
              max:
                type: number
            type: object
        type: object
      displayName:
        type: string
      gpu:
        properties:
          temp:
            items:
              properties:
                main:
                  type: number
              type: object
            type: array
        type: object
      name:
        type: string
      network:
        properties:
          usage:
            properties:
              receiveRate:
                type: integer
              transmitRate:
                type: integer
            type: object
        type: object
      ram:
        properties:
          load:
            properties:
              main:
                type: number
            type: object
        type: object
      zone:
        description: |-
          Zone is the name of the zone where the host is located.
          This field might not yet be present in all responses, in which case ZoneID should be used.
        type: string
    type: object
  body.K8sStats:
    properties:
      clusters:
        items:
          $ref: '#/definitions/body.ClusterStats'
        type: array
      podCount:
        type: integer
    type: object
  body.RamCapacities:
    properties:
      total:
        type: integer
    type: object
  body.Stats:
    properties:
      k8s:
        $ref: '#/definitions/body.K8sStats'
    type: object
  body.Status:
    properties:
      hosts:
        items:
          $ref: '#/definitions/body.HostStatus'
        type: array
    type: object
  body.TimestampedCapacities:
    properties:
      capacities:
        $ref: '#/definitions/body.Capacities'
      timestamp:
        type: string
    type: object
  body.TimestampedGpuInfo:
    properties:
      gpuInfo:
        $ref: '#/definitions/body.GpuInfo'
      timestamp:
        type: string
    type: object
  body.TimestampedStats:
    properties:
      stats:
        $ref: '#/definitions/body.Stats'
      timestamp:
        type: string
    type: object
  body.TimestampedStatus:
    properties:
      status:
        $ref: '#/definitions/body.Status'
      timestamp:
        type: string
    type: object
  host_api.GpuInfo:
    properties:
      bus:
        type: string
      deviceId:
        type: string
      name:
        type: string
      passthrough:
        type: boolean
      slot:
        type: string
      vendor:
        type: string
      vendorId:
        type: string
    type: object
info:
  contact: {}
paths:
  /capacities:
    get:
      consumes:
      - application/json
      description: GetCapacities Capacities
      parameters:
      - description: "n"
        in: query
        name: "n"
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/body.TimestampedCapacities'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/body.BindingError'
      summary: GetCapacities Capacities
      tags:
      - Capacities
  /hostInfo:
    get:
      consumes:
      - application/json
      description: Register resource
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Register resource
      tags:
      - Register
  /internal/gpuInfo:
    get:
      consumes:
      - application/json
      description: GetGpuInfo GPU info
      parameters:
      - description: "n"
        in: query
        name: "n"
        type: integer
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/body.TimestampedGpuInfo'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/body.BindingError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/app.ErrorResponse'
      summary: GetGpuInfo GPU info
      tags:
      - GPU info
  /stats:
    get:
      consumes:
      - application/json
      description: GetStats Stats
      parameters:
      - description: "n"
        in: query
        name: "n"
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/body.TimestampedStats'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/body.BindingError'
      summary: GetStats Stats
      tags:
      - Stats
  /status:
    get:
      consumes:
      - application/json
      description: GetStatus Status
      parameters:
      - description: "n"
        in: query
        name: "n"
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/body.TimestampedStatus'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/body.BindingError'
      summary: GetStatus Status
      tags:
      - Status
swagger: "2.0"
