name: Build and push image

on:
  workflow_dispatch:
  push:
    branches:
      - 'build'
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-and-push-image.yml'
      - '**.go'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.cloud.cbh.kth.se/sys/sys-api:latest
